### ISSUE TITLE
Relasjoner: eksempler mangler

### ISSUE THREAD

**Issue by stigbd** [difi/skos-ap-no#111]
Det mangler eksempler både i spesifikasjonen og eksempel-folder på begrepsrelasjoner og tilhørende spesialiseringer. 

Slike eksempler er kritiske når vi no skal gå i gang med å implementere støtte for relasjoner i data.norge.no og registreringsløsningen.

**Comment by jimjyang** [comment]
@stigbd Har nå lagt inn eksempler i spesifikasjonen, se f.eks. under [GeneriskRelasjon.overordnetBegrep](https://data.norge.no/specification/skos-ap-no-begrep/#GeneriskRelasjon_overordnetBegrep) og [PartitivRelasjon.overordnetBegrep](https://data.norge.no/specification/skos-ap-no-begrep/#PartitivRelasjon_overordnetBegrep). 

Skal "litt etter hvert" legge ut komplette eksempler/eksempelfiler, sammen med oppdaterte shacl-regler.

**Comment by jimjyang** [comment]
@stigbd Komplette eksempler (i RDF Turtle) på alle tre typer begrepsrelasjoner er nå lagt ut under mappa[ examples](https://github.com/Informasjonsforvaltning/skos-ap-no-begrep/tree/develop/examples), med oppdaterte shacl og ontologi. 

Kan du se om det er ok, før jeg lager PR for å merge develop til v1?

**Comment by stigbd** [comment]
Veldig bra! Eg har ikkje detaljstuderte dette, men det er akkurat det vi er ute etter.

Tenker at det kunne vore fint å også legg inn i Vedlegg A, enten inn i A.1 eller dedikert del.
