### ISSUE TITLE
Reglene legger ikke tilrette for flere språk

### ISSUE THREAD

**Issue by shenluna** [difi/skos-ap-no#123]
Eksempel på regel som er feil ved multi-språk:

```
sh:property [ # fagområde
      sh:name "fagområde"@nb , "subject field"@en ;
      sh:path dct:subject ;
      sh:nodeKind sh:Literal ;
      sh:maxCount 1 ;
      sh:severity sh:Violation ;
      sh:message "Begrepet kan ha maks. 1 fagområde (dct:subject), som skal være Literal"@nb ;
      ] ;
```

Eksempel på begrep som validerer feil grunnet regelen over: https://concepts.staging.fellesdatakatalog.digdir.no/concepts/e6be8df5-5a1b-3ae3-84ba-16e2a15bdab9

**Comment by jimjyang** [comment]
Dette er en feil i den grunnleggende forvaltningsstandarden som denne er en teknisk implementering av, se [dette Issuet](https://github.com/Informasjonsforvaltning/forvaltningsstandard-begrepsbeskrivelser/issues/79).

**Comment by stigbd** [comment]
@jimjyang  Kan vi vurdere å la shacl-reglene rette opp i dette ved å tilpasse regelen til fakta på bakken? Så tar vi forvaltningsstandarden etter kvart?

**Comment by jimjyang** [comment]
Ja, selvsagt. Skal ta det litt senere (må få unna noen andre saker først). 
Har ellers foreslått en revisjon av forvaltningsstandarden ila. 2022.

**Comment by jimjyang** [comment]
Endret shacl-reglene (flere) nå, og sjekket at eksemplet ikke gir feil nå.
