### ISSUE TITLE
dct:identifier skal ha range rdfs:Literal

### ISSUE THREAD

**Issue by stigbd** [difi/skos-ap-no#127]
dct:identifier skal ha range rdfs:Literal. I dag er det ikkje slik det er spekka:
https://data.norge.no/specification/skos-ap-no-begrep/#Begrep_identifikater

Også shacl-shapes bør endres:
https://github.com/Informasjonsforvaltning/skos-ap-no-begrep/blob/4ad72ed0eee9456a00e9d5d878eb3094d593e9a1/shacl/SKOS-AP-NO-Begrep-shape_shape_v1.ttl#L63-L70

Med ei slik endring vil vi vere i samsvar med https://data.norge.no/specification/dcat-ap-no/#Datasett-identifikator

**Comment by jimjyang** [comment]
Del 1 (selv spesifikasjonen), løser vi ifm. revisjonsarbeidet som nå startes opp. 

Del 2 (shacl) løser vi nå, ved å endre fra `sh:IRI` til `sh:IRIOrLiteral`.

**Comment by jimjyang** [comment]
I høringsversjonen er identifikator av datatype `xsd:anyURI`, dvs. i praksis `rdfs:Literal typed as xsd:anyURI`.

Eks. `<> dct:identifier "https://example.org/exIdentifier"^^xsd:anyURI .`

**Comment by jimjyang** [comment]
Lukker dette issuet.
