### ISSUE TITLE
[skos-ap-no-begrep] Vaghet i betydningsbeskrivelse.omfang.tekst og betydningsbeskrivelse.omfang-uri

### ISSUE THREAD

**Issue by marittor** [difi/skos-ap-no#14]
Problembeskrivelse: 
I dagens SKOS-AP.NO forvaltningsstandard er de to feltene i standarden beskrevet på følgende måte: 

Felt | Betydningsbeskrivelse.omfang.URI | Betydningsbeskrivelse.omfang.tekst |
------------ | ------------- | -------------
URI til definisjon | skosno:omfang | skosno:omfang 
SKOS (RDF turtle)-representasjon | <> skosno:omfang <> . | <> skosno:omfang “”@nb . 
Datatype (med ev. URI til definisjon) | URI | rdf:Literal
Merknad | RDF Term (Literal or URI) | RDF Term (Literal or URI)

Når vi prøver å praktisere dette, kommer det ikke klart fram/er ikke presist nok skille på URI og tekst. URITekst datatypen brukes også for kilde, se eks betydningsbeskrivelse.kildebeskrivelse.kilde.URI i standarden her: https://doc.difi.no/data/begrep-skos-ap-no/#_betydningsbeskrivelse_kildebeskrivelse_kilde_uri . Her har man skilt mellom rdfs:label og rdfs:seeAlso. Hvorfor er det ulikt mellom disse to innbyrdes i standarden? Er det gjort bevisst, eller burde omfang vært løst på samme måte som for kilde her?

**Comment by marittor** [comment]
Vi vet ikke ennå om dette bør løses likt som kildebeskrivelse, men det bør gjøres en endring, f. eks ta med noe a la dct:source (men om det så skal stå label og seeAlso er vi usikker på eller om dette skal gjøres annerledes for omfang - finnes det noe mer presist enn seeAlso?). Bør vel også ta med klassen betydningsbeskrivelse og hhv definisjon og alternativ formulering.

Følgende feilstavelser er også oppdaget: 
rdfs:Literal (liten l) for feltet: Betydningsbeskrivelse.omfang.tekst må rettes. 

Feilstaving i  skos-repr. i feltet: Betydningsbeskrivelse.kildebeskrivelse.kilde.tekst (står altearnativ..)

**Comment by tormodv** [comment]
Vaghet er ikke nødvendighvis et dårlig ting, selv der man kombinerer to datatyper som er forholdshvis vide. Men la oss se dette fra instansens og den videre innlesingen av dataene side.
Dersom man skriver en beskrivende tekst i dette feltet, så skal man sette på en _språkkode_. Dette medfører at verdien kun tilfredstiller påstanden om at dette er en rdfs:Litteral. 
Hvis vi derimot setter inn en url, så kan denne types på vanlig måte av den som skriver instansen, f. eks: "http://ebu.ch/terms/i45g6/"^^xsd:anyUri
Det er dermed helt entydig at dette tilfredstiller den andre påstanden om at feltet er en URI. Når man leser instansen får man en tydelig beskjed om at man kkan betrakte innholdet som en referanse til en ressurs. Så i praksis skulle det ikke være en reel mulighet for at man blander kortene her. 
Denne typen dobble range er veldig vanlig, jeg har selv brukt denne flere ganger i diverse standarder i den Europeiske Kringkastingsunionen, for å tilfredstille de forskjellige medlemers ulike infrastruktur.

**Comment by jimjyang** [comment]
Løsningsforslag: Vi kommer til å beskrive "Betydningsbeskrivelse.omfang.tekst" hhv. "Betydningsbeskrivelse.omfang.URI" på tilsvarende måte og med tilsvarende detaljeringsgrad som for "Betydningsbeskrivelse.kildebeskrivelse.kilde.tekst" hhv. "Betydeningsbeskrivelse.kildebeskrivelse.kilde.URI".

**Comment by jimjyang** [comment]
Utført, lukkes.
