### ISSUE TITLE
[skosno-turtle.owl] Mulig utilsiktet konsekvens av arvede egenskaper.

### ISSUE THREAD

**Issue by tormodv** [difi/skos-ap-no#15]
I definisjon av skos:Concept har man lagt inn følgende begrensning: 
[ rdf:type owl:Restriction ;
       owl:onProperty skosno:underordnetBegrep ;
        owl:maxQualifiedCardinality "1"^^xsd:nonNegativeInteger ;
         owl:onClass skos:Concept
   ] ,

Med all respekt for arbeidet som er gjort, så skjønner jeg ikke helt hva man ønsker å gjøre her. SKOS i sin originale form, begrenser ikke bruk av dette attributtet. Et generelt begrep kan ha mange underordnede begreper slik jeg ser det. Dersom man prøver å legge inn instanser for det, går det jo helt fint med den første, tilsynelatende med nummer to går det like fint, men nå trer det inn en bieffekt i alle fall med HermiT reasoner er at den prøver å få de to påstandene fra instansene og klassedefinisjonen ved å legge til en påstand om at de to underordnede termene er den samme termen, (same individual as).
Er det dette man mener, eller kunne man kommet like langt med:
[ rdf:type owl:Restriction ;
  owl:onProperty skosno:underordnetBegrep ;
  owl:someValuesFrom skos:Concept
 ] ,

**Comment by jimjyang** [comment]
Ja, det er feil her.

Det som egentlig skulle uttrykkes er "fra en Begrepsrelasjon (ikke et Begrep) kan det være maks. ett underordnetBegrep". Jf. UML-modellen https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/#vedlegga. Begrepsrelasjon er en abstrakt klasse i UML-modellen (som ble laget for å kunne ha med administrativ info sistOppdatert).  

Jeg syns ikke det er nødvendig å ha noen begrensning på maks. antall underordnetBegrep. 

Tilsvarende bør heller ikke være noen begrensning på maks. antall overordnetBegrep. Et begrep kan tilhøre / knyttes til flere begrepssystemer og dermed ha flere ulike overoendetBegrep.

**Comment by jimjyang** [comment]
Fikset, lukkes.
