### ISSUE TITLE
Døde lenker - Kap 2.2 - "anbefalt term", "definisjon", etc. 

### ISSUE THREAD

**Issue by rockphotog** [difi/skos-ap-no#208]
Fra tabellen: 

> [anbefalt term](https://termbasen.standard.no/term/167505078703413/nb?origin=%2Fsearch-results%3FsearchText%3Danbefalt%2Bterm%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100)
> [definisjon](https://termbasen.standard.no/term/167505060009870/nb?origin=%2Fsearch-results%3FsearchText%3Ddefinisjon%26icsCodes%3D%26sources%3D%26start%3D0%26range%3D100)

Det kan se ut til at dette gjelder mange lenker i tabellene nedover. 

Jeg kjenner til at Standard Norge har revidert sine nettsider.

**Comment by jimjyang** [comment]
@rockphotog Takk skal du ha!
