### ISSUE TITLE
[spørsmål] domener/dct:subject som xs:string?

### ISSUE THREAD

**Issue by OyvindLGjesdal** [difi/skos-ap-no#37]
Jobber med mapping av eksisterende terminologiske data og lurer på hvordan domener henger sammen med skosno.

Sånn jeg forstår det ut i fra modellen, ville jeg tenkt at overordnede hierarkiske domener også er av type `skos:Concept` (gjerne fra et eksisterende eksterne kontrollerte vokabular) og at en kunne pekt på disse med egenskapen dct:subject <uri-til-concept>, men at den her er er begrenset til språkspesifikk tekst. 

Beskrivelsen fra dcterms har en preferanse mot kontrollerte verdier/urier.
```
Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
```

Er det slik at  bruk av domene egentlig betyr at en skal bruke relasjonene fra skosno (xkos:generalizes, xkos:hasPart) og at domener dermed blir relaterte Begrep? Altså at en ikke skiller domene/begrep?

Takk for arbeidet med modellen!

**Comment by jimjyang** [comment]
Hvis jeg forstår spørsmålet ditt rett handler det om bruk av feltet "Begrep.fagområde" (jf. [datamodell](https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/#vedlegga) som denne standarden implementerer).  

"Fagområde" i denne standarden her er mappet til dct:subject som vi fant var den semantisk nærmeste å bruke. 

Som ditt sitat sier, er det anbefalt å peke til et kontrollert vokabular, men arbeidsgruppen som utarbeidet _[Forvaltningsstandard for begrepsbeskrivelser](https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/)_ som denne standarden implementerer ved å bruke SKOS, ikke klarte å standardisere "fagområde" og dermed ikke mulig å peke til none (eksisterende eller nye) kontrollerte vokabularer for "fagområde". "Fagområde" er derfor (foreløpig) modellert med datatype TekstMedSpråkkode og ikke (også) som URI.

**Comment by OyvindLGjesdal** [comment]
Takk, jeg skal lese nøyere gjennom _Forvaltningsstandard for begrepsbeskrivelser_.

Jeg tror at jeg har litt problemer med å skille mellom skosno:omfang (som kan gå til eksterne vokabular), dct:subject og skosno:bruksområde og hvordan jeg skal bruke de.

**Comment by jimjyang** [comment]
Se forresten også [forklaring på "omfang" i Veileder for bruk av forvaltningsstandard for begrepsbeskrivelser](https://doc.difi.no/data/veileder-for-begrepsbeskrivelser/#omfang). Omfang kan ofte brukes til å oppgi lovlige verdier (f.eks. sivilstand) bl.a. i form av standardiserte kodeverk/klassifikasjonssystemer/osv. Derfor valgte arbeidsgruppe å ha datatype URITekst (URI eller tekst) for "omfang". 

"Bruksområde" er enda vanskeligere (enn "fagområde") å standardisere og etablere kontrollerte vokabularer for. Derfor er det også TekstMedSpråkkode som datatype for "bruksområde".

**Comment by jimjyang** [comment]
@OyvindLGjesdal Jeg lukker denne nå, du får si fra hvis det er uavklart.
