### ISSUE TITLE
endre skosno:Betydningsbeskrivelse til skosno:betydningsbeskrivelse?

### ISSUE THREAD

**Issue by OyvindLGjesdal** [difi/skos-ap-no#51]
Siden dette er en property og ikke en klasse burde en rename denne? Er ingenting i veien for å bruke upper case i propertynavn som en gjør i både wikidata og cidoc-CRM, men når navnet ikke selv indikerer at det er en property er det lett å tenke at den er en klasse.

**Comment by jimjyang** [comment]
Fikset
