### ISSUE TITLE
presisering av namespace-uri for skosno:

### ISSUE THREAD

**Issue by OyvindLGjesdal** [difi/skos-ap-no#55]
Dette er muligens relatert til #49 og at publisering er er under arbeid.

Jeg ønsker å kjøre [rdfunit](https://github.com/AKSW/RDFUnit) (eller laste instanser inn i Protege sammen med ontologien) med ontology/skosno-turtle.owl for å se fremgang/validitet av eksporter.

I turtle-fil er skosno namespace definert som `http://difi.no/skosno#`

I eksempel fra dokumentasjon er
`https://data.norge.no/vocabulary/skosno#` brukt , mens `data.norge.no/vocabulary/skosno#` er nevnt i tekst som fremtidig sted for publikasjon.

Om jeg ønsker å teste nå blir det da mot uri i turtle-fil, men er det den andre som blir den gjeldende URI? Og bruker en da namespace med eller uten https?

**Comment by jimjyang** [comment]
@OyvindLGjesdal Det stemmer at det er 'https://data.norge.no/vocabulary/skosno#' som er det fremtidige publiseringsstedet. turtle-filen er dessverre ikke oppdatert (den er heller ikke komplett).

**Comment by OyvindLGjesdal** [comment]
Det med https versus https tenkte eg på [denne  blogposten](https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/) og om dette har endret seg

**Comment by jimjyang** [comment]
Vi bruker https i samsvar med anbefalingen i [Referansekatalogen](https://www.difi.no/referansekatalogen/grunnleggende-datakommunikasjon).

**Comment by OyvindLGjesdal** [comment]
Da forholder eg meg til https://data.norge.no/vocabulary/skosno# som den riktige URI
