### ISSUE TITLE
Lenke brukt i standarden gir 404: https://www.digdir.no/digitale-felleslosninger/forvaltningsstandard-begrepsbeskrivelser/1649

### ISSUE THREAD

**Issue by stigbd** [difi/skos-ap-no#87]
Forsøker å gå til ressursen som er lenka til i avsnittet "Formål, omfang og avgrensninger":
> Standarden spesifiserer hvordan begrepsbeskrivelser som er utformet i henhold til Forvaltningsstandard for begrepsbeskrivelser, 
men får "Vi finner ikke siden".

**Comment by jimjyang** [comment]
Obs på at det er flere lenker som ikke virker nå.

**Comment by stigbd** [comment]
Vi bør endre den til å peike på https://data.norge.no/specification/forvaltningsstandard-begrepsbeskrivelser/
